// ECOSAFE — copy (PL / EN)
const COPY = {
  pl: {
    nav: {
      home: "Start",
      bdo: "BDO",
      doradztwo: "Doradztwo",
      bhp: "Szkolenia BHP",
      kontakt: "Kontakt",
    },
    hero: {
      eyebrow: "BDO · Ochrona środowiska · BHP",
      title_pre: "Pomagam firmom",
      title_em: "rozumieć",
      title_post: "środowisko i bezpieczeństwo — spokojnie oraz praktycznie.",
      lead: "Misją ECOSAFE jest pomagać ludziom i firmom rozumieć BHP oraz ochronę środowiska w prosty i praktyczny sposób, żeby mogli prowadzić firmy w bezpieczny, świadomy i odpowiedzialny sposób.",
      cta_primary: "Zapytaj o wycenę",
      cta_secondary: "Sprawdź swoją firmę",
      caption: "Dla jednoosobowych działalności, średnich i dużych firm — bez urzędowego tonu.",
    },
    marquee: ["BDO", "Ewidencja odpadów", "Sprawozdania roczne", "BHP online", "Doradztwo", "KOBiZE", "Opakowania", "Audyt środowiskowy"],
    pillars: {
      eyebrow: "Trzy obszary wsparcia",
      title_pre: "Więcej wiedzy,",
      title_em: "więcej spokoju.",
      lead: "Każda firma ma obowiązki. Nie każda wie, od czego zacząć. Wspieram w trzech obszarach, które często się przeplatają - jasno i krok po kroku.",
      items: [
        {
          n: "01",
          tag: "BDO",
          title: "Obsługa BDO",
          body: "Prowadzę ewidencję odpadów, pilnuję terminów, przygotowuję sprawozdania roczne i karty przekazania odpadów. Ty zajmujesz się firmą — ja rejestrem.",
          bullets: ["Ewidencja odpadów", "Sprawozdania roczne", "Rejestracja i aktualizacje", "Indywidualne szkolenia pracowników z obsługi BDO"],
        },
        {
          n: "02",
          tag: "Środowisko",
          title: "Doradztwo środowiskowe",
          body: "Tłumaczę wymagania prawne na język, który rozumie zarząd i pracownik produkcji. Pomagam wdrożyć to, co naprawdę jest potrzebne.",
          bullets: ["KOBiZE i opłaty środowiskowe", "Decyzje i pozwolenia", "Rejestracja i aktualizacje", "Audyty i wdrożenia ulepszeń"],
        },
        {
          n: "03",
          tag: "BHP",
          title: "Szkolenia BHP online",
          body: "Kursy dla tych, którzy chcą uzupełnić lub uporządkować swoją wiedzę z BHP. Szkolenia są omawiane w sposób jasny i klarowny.",
          bullets: ["Wsparcie po szkoleniu", "Dla pracowników i kadry", "Dostęp 24/7", "Indywidualne szkolenia z BDO"],
        },
      ],
    },
    quiz: {
      eyebrow: "3–4 minuty",
      title: "Sprawdź, co Twoja firma powinna mieć w porządku.",
      lead: "7 pytań z zakresu gospodarki odpadami, opakowań i BHP. Na końcu dostajesz diagnozę, listę obowiązków i rekomendowane działania.",
      start: "Zacznij ankietę",
      q: [
        {
          q: "Czy Twoja firma w toku działalności wytwarza odpady inne niż komunalne?",
          hint: "Np. opakowania po surowcach, zużyty sprzęt elektryczny, oleje, tonery, odpady produkcyjne, budowlane, medyczne.",
          opts: ["Tak, regularnie", "Sporadycznie / w niewielkich ilościach", "Nie", "Nie wiem"],
        },
        {
          q: "Czy prowadzisz ewidencję wytwarzanych odpadów w systemie BDO?",
          hint: "Ewidencja obejmuje karty ewidencji odpadów (KEO) oraz karty przekazania odpadów (KPO).",
          opts: ["Tak, na bieżąco", "Prowadzimy, ale z opóźnieniami", "Nie prowadzimy", "Nie wiem, czy nas to dotyczy"],
        },
        {
          q: "Czy wprowadzasz na rynek produkty w opakowaniach lub same opakowania?",
          hint: "Dotyczy producentów, importerów, dystrybutorów pakujących towary we własne opakowania.",
          opts: ["Tak", "Nie", "Nie jestem pewien/pewna"],
        },
        {
          q: "Czy w ostatnim roku składałeś/aś sprawozdanie środowiskowe (BDO, KOBiZE, opłata środowiskowa)?",
          opts: ["Tak, wszystkie wymagane", "Tak, ale nie wszystkie", "Nie składałem/am", "Nie wiem, co mnie dotyczy"],
        },
        {
          q: "Czy szkolenia BHP w Twojej firmie są aktualne?",
          hint: "Szkolenia wstępne dla nowych pracowników oraz okresowe dla pozostałych zatrudnionych.",
          opts: ["Tak, wszyscy pracownicy mają aktualne", "Część osób ma nieaktualne", "Nie mamy aktualnych szkoleń", "Pracuję sam/a"],
        },
        {
          q: "Czy wiesz, jakie obowiązki BHP dotyczą Twojej działalności?",
          hint: "Np. ocena ryzyka zawodowego, instrukcje stanowiskowe, badania lekarskie, środki ochrony indywidualnej.",
          opts: ["Tak, mam pełną dokumentację", "Znam część, reszta wymaga uporządkowania", "Nie — potrzebuję wsparcia", "Nie dotyczy mojej działalności"],
        },
        {
          q: "Kiedy ostatnio firma przechodziła kontrolę (WIOŚ, PIP, sanepid)?",
          opts: ["W ostatnim roku — bez uwag", "W ostatnim roku — z uwagami", "Ponad rok temu", "Nigdy nie było kontroli"],
        },
      ],
      result_title: "Wynik diagnozy:",
      risk_label: "Poziom ryzyka",
      risk_low: "Niski",
      risk_mid: "Średni",
      risk_high: "Wysoki",
      duties_label: "Prawdopodobne obowiązki",
      services_label: "Rekomendowane usługi ECOSAFE",
      again: "Wypełnij jeszcze raz",
      book: "Zapytaj o wycenę",
    },
    about: {
      eyebrow: "Kto za tym stoi",
      name: "Angelika Siołek",
      role: "Specjalistka BHP i ochrony środowiska",
      body_1: "Prowadzę ECOSAFE, bo zauważyłam, że firmy nie potrzebują kolejnej ustawy do przeczytania — potrzebują kogoś, kto powie: „zrób to, to i to, w takiej kolejności, do tego dnia\".",
      body_2: "Dbam o to, aby zasoby naturalne były wykorzystywane rozsądnie — tak, aby mogły służyć nie tylko nam, ale również naszym dzieciom i przyszłym pokoleniom. Bo czysta przyszłość zaczyna się od świadomych decyzji podejmowanych dziś.",
      stats: [
        { n: "500+", label: "wykonanych sprawozdań" },
        { n: "12", label: "lat doświadczenia" },
        { n: "0", label: "kar po kontroli" },
      ],
    },
    testimonials: {
      eyebrow: "Opinie",
      title: "Klienci mówią to samo — najpierw ulga, potem spokój.",
      items: [
        { q: "Przez trzy lata nie wiedziałam, czy w ogóle muszę mieć BDO. Anna wytłumaczyła mi to w 20 minut i przejęła wszystko.", who: "Magda, salon fryzjerski, Kraków" },
        { q: "Kontrola WIOŚ bez wpadki. Papiery były gotowe dzień wcześniej.", who: "Tomasz, zakład stolarski, 12 osób" },
        { q: "Szkolenia BHP online były hitem — ekipa zrobiła je między zmianami, nikt się nie buntował.", who: "Karolina, HR, firma produkcyjna 80 osób" },
      ],
    },
    cta: {
      title_pre: "Zacznijmy od",
      title_em: "rozmowy.",
      lead: "Opisz krótko swój zakres — przygotuję wycenę i propozycję współpracy. Zazwyczaj odpowiadam tego samego dnia.",
      button: "Zapytaj o wycenę",
    },
    footer: {
      tag: "BDO · Ochrona środowiska · BHP",
      rights: "© 2026 ECOSAFE. Wszystkie prawa zastrzeżone.",
    },

    // BDO page
    bdo: {
      eyebrow: "Usługa 01",
      title_pre: "BDO —",
      title_em: "ja się tym zajmę.",
      lead: "Rejestr, ewidencja, sprawozdania, KPO. Poprowadzę to za Ciebie.",
      scope_title: "Co obejmuje obsługa",
      scope: [
        { t: "Rejestracja w BDO", d: "Pełna rejestracja podmiotu w Bazie danych o produktach i opakowaniach oraz o gospodarce odpadami.", price: "299 zł" },
        { t: "Prowadzenie ewidencji", d: "Bieżąca ewidencja odpadów, KPO, KPOK. Wystawianie i pilnowanie, żeby wszystko się zgadzało.", price: "od 99 zł / mies." },
        { t: "Aktualizacja danych", d: "Aktualizacja wpisu w BDO przy zmianach w firmie — adres, zakres działalności, odpady.", price: "199 zł" },
        { t: "Wykreślenie z BDO + sprawozdanie", d: "Kompleksowe zamknięcie rejestru wraz z końcowym sprawozdaniem.", price: "299 zł" },
        { t: "Sprawozdanie odpadowe", d: "Przygotowanie i złożenie rocznego sprawozdania w terminie. Bez paniki w marcu.", price: "od 199 zł" },
        { t: "Indywidualne szkolenie BDO", d: "Szkolenie z obsługi systemu BDO dostosowane do Twojej firmy.", price: "od 599 zł" },
      ],
      timeline_title: "Kalendarz obowiązków — rok w BDO",
      timeline: [
        { m: "Styczeń", d: "Podsumowanie roku poprzedniego. Sprawdzenie kompletności ewidencji.", tag: "Start" },
        { m: "15 marca", d: "Sprawozdanie o wytwarzanych odpadach za rok poprzedni.", tag: "Deadline" },
        { m: "31 marca", d: "Sprawozdanie o opakowaniach (jeżeli dotyczy).", tag: "Deadline" },
        { m: "Kwiecień", d: "Opłaty środowiskowe — KOBiZE i marszałek.", tag: "Opłaty" },
        { m: "Wrzesień–listopad", d: "Typowy sezon kontroli WIOŚ. Dokumenty muszą być na bieżąco.", tag: "Kontrole" },
        { m: "Grudzień", d: "Domknięcie roku, archiwizacja, przygotowanie do sprawozdań.", tag: "Domknięcie" },
      ],
    },

    doradztwo: {
      eyebrow: "Usługa 02",
      title_pre: "Doradztwo",
      title_em: "środowiskowe.",
      lead: "KOBiZE, opakowania, decyzje, pozwolenia, opłaty. Wszystko, czego wymaga prawo — bez prawniczego bełkotu.",
      scope_title: "Zakres doradztwa",
      scope: [
        { t: "KOBiZE", d: "Raport do Krajowej bazy o emisjach — ustalenie, czy jesteś zobowiązany i przygotowanie raportu." },
        { t: "Opakowania i ROP", d: "Rozszerzona odpowiedzialność producenta. Rozliczenia, umowy z organizacją odzysku." },
        { t: "Pozwolenia i decyzje", d: "Wsparcie w uzyskiwaniu decyzji środowiskowych i pozwoleń sektorowych." },
        { t: "Audyt środowiskowy", d: "Przegląd obecnej sytuacji firmy, lista ryzyk i konkretny plan działań." },
      ],
    },

    bhpPage: {
      eyebrow: "Usługa 03",
      title_pre: "Szkolenia BHP",
      title_em: "online.",
      lead: "Zgodne z przepisami. Bez całodniowych warsztatów w sali konferencyjnej. Kursy wstępne i okresowe dostępne 24/7.",
      courses_title: "Dostępne kursy",
      courses: [
        { t: "Kursy BHP online", len: "od 45 min", price: "wycena indyw.", desc: "Wstepne i okresowe kursy BHP dostępne 24/7 — dla pracowników biurowych, kadry, stanowisk robotniczych." },
        { t: "Audyt warunków pracy", len: "1–3 dni", price: "wycena indyw.", desc: "Wszechstronna analiza stanowisk pracy, identyfikacja zagrożeń, ocena procedur BHP i sprójności dokumentacji z prawem." },
        { t: "Ocena ryzyka zawodowego", len: "wg zakresu", price: "wycena indyw.", desc: "Tworzenie dokumentacji związanej z zagrożeniami występującymi na danych stanowiskach pracy." },
        { t: "Szkolenie wstępne / okresowe", len: "45 min – 8 godz.", price: "wycena indyw.", desc: "Certyfikat w PDF po zdanym teście. Zgodne z przepisami." },
      ],
      how_title: "Jak to działa",
      how: [
        { n: "01", t: "Rejestracja", d: "Zakładasz konto, dodajesz pracowników (lub siebie)." },
        { n: "02", t: "Kurs online", d: "Wideo + materiały + quizy. Można w kilku podejściach." },
        { n: "03", t: "Test końcowy", d: "Prosty, rzetelny. Zaliczenie od 80%." },
        { n: "04", t: "Certyfikat", d: "PDF z numerem, zgodny z przepisami. Natychmiast na mailu." },
      ],
    },

    kontakt: {
      eyebrow: "Kontakt",
      title_pre: "Napisz albo",
      title_em: "zadzwoń.",
      lead: "Najczęściej odpowiadam tego samego dnia. Opisz krótko firmę i zakres — przygotuję wycenę i plan działań.",
      form_name: "Imię",
      form_email: "Email",
      form_company: "Firma (opcjonalnie)",
      form_topic: "Temat",
      form_topic_opts: ["BDO", "Doradztwo środowiskowe", "Szkolenia BHP", "Coś innego"],
      form_message: "Wiadomość",
      form_submit: "Wyślij wiadomość",
      form_success: "Dzięki! Odezwę się w ciągu 24 godzin.",
      errors: {
        name: "Podaj imię",
        email: "Podaj poprawny email",
        message: "Napisz kilka zdań, żebym wiedziała, z czym pomóc",
      },
      contact_blocks: [
        { t: "Email", v: "kontakt@ecosafe.com.pl" },
        { t: "Telefon", v: "+48 791 045 130" },
        { t: "Godziny", v: "Pn–Pt · 9:00–17:00" },
        { t: "NIP", v: "6443343386" },
        { t: "REGON", v: "542094091" },
      ],
    },
  },

  en: {
    nav: {
      home: "Home",
      bdo: "Waste (BDO)",
      doradztwo: "Advisory",
      bhp: "Safety training",
      kontakt: "Contact",
    },
    hero: {
      eyebrow: "Waste · Environment · Workplace safety",
      title_pre: "I help businesses",
      title_em: "understand",
      title_post: "environment and safety — simply.",
      lead: "ECOSAFE's mission is to help people and companies understand workplace safety and environmental protection in a simple, practical way — so they can act safer, more consciously and more responsibly.",
      cta_primary: "Request a quote",
      cta_secondary: "Check your company",
      caption: "For sole traders, mid-size and large companies — no bureaucratic tone.",
    },
    marquee: ["Waste register", "BDO", "Annual reports", "Online safety training", "Advisory", "KOBiZE", "Packaging", "Environmental audit"],
    pillars: {
      eyebrow: "Three areas of support",
      title_pre: "Less panic,",
      title_em: "more sense.",
      lead: "Every business has obligations. Not every one knows where to start. I work across three areas that often overlap — and I'll walk you through them, step by step.",
      items: [
        {
          n: "01",
          tag: "Waste",
          title: "BDO — waste register",
          body: "I keep your waste records, watch the deadlines, prepare annual reports and waste transfer cards. You run the business — I run the register.",
          bullets: ["Records & transfer cards", "Annual reports", "Registration & updates", "Inspection support"],
        },
        {
          n: "02",
          tag: "Environment",
          title: "Environmental advisory",
          body: "I translate legal requirements into language both the board and the shop floor understand. And I help you put in place only what's actually needed.",
          bullets: ["KOBiZE & fees", "Decisions & permits", "Packaging & EPR", "Audits & rollouts"],
        },
        {
          n: "03",
          tag: "Safety",
          title: "Online safety training",
          body: "Initial and periodic courses available 24/7, without pulling people off work for a whole day. Certificate on passing, fully compliant.",
          bullets: ["Initial & periodic", "Workers & managers", "24/7 access", "PDF certificate"],
        },
      ],
    },
    quiz: {
      eyebrow: "3–4 minutes",
      title: "Check what your company should have in order.",
      lead: "7 questions on waste, packaging and workplace safety. At the end you get a diagnosis, a list of duties and recommended next steps.",
      start: "Start the survey",
      q: [
        {
          q: "Does your company generate waste other than municipal?",
          hint: "E.g. packaging, used electronics, oils, toners, production/construction/medical waste.",
          opts: ["Yes, regularly", "Occasionally / small amounts", "No", "Not sure"],
        },
        {
          q: "Do you keep waste records in the BDO system?",
          hint: "Waste records include KEO cards and KPO transfer cards.",
          opts: ["Yes, up to date", "Yes, but with delays", "No, we don't", "Unsure if it applies"],
        },
        {
          q: "Do you place products in packaging on the market, or packaging itself?",
          hint: "Applies to producers, importers and distributors packing goods in their own packaging.",
          opts: ["Yes", "No", "Not sure"],
        },
        {
          q: "Did you file required environmental reports in the last year (BDO, KOBiZE, environmental fee)?",
          opts: ["Yes, all of them", "Yes, but not all", "I did not file", "Unsure what applies"],
        },
        {
          q: "Is your team's safety training up to date?",
          hint: "Initial training for new hires and periodic training for the rest.",
          opts: ["Yes, everyone is current", "Some are out of date", "No, none are current", "I work alone"],
        },
        {
          q: "Do you know which workplace safety obligations apply to your business?",
          hint: "E.g. risk assessment, workstation instructions, medical checks, PPE.",
          opts: ["Yes, full documentation", "Partial — needs tidying", "No — I need help", "Doesn't apply to me"],
        },
        {
          q: "When was your company last inspected (environmental, labour, sanitary)?",
          opts: ["In the last year — no findings", "In the last year — with findings", "Over a year ago", "Never"],
        },
      ],
      result_title: "Diagnosis:",
      risk_label: "Risk level",
      risk_low: "Low",
      risk_mid: "Medium",
      risk_high: "High",
      duties_label: "Likely obligations",
      services_label: "Recommended ECOSAFE services",
      again: "Take it again",
      book: "Request a quote",
    },
    about: {
      eyebrow: "Who's behind it",
      name: "Angelika Siołek",
      role: "Safety & environment specialist",
      body_1: "I run ECOSAFE because I noticed that businesses don't need another regulation to read — they need someone to say: „do this, then this, then this, by this date\".",
      body_2: "I take care that natural resources are used sensibly — so they can serve not only us, but our children and future generations. Because a clean future starts with conscious decisions made today.",
      stats: [
        { n: "120+", label: "companies supported" },
        { n: "8", label: "years of experience" },
        { n: "0", label: "fines post-inspection" },
      ],
    },
    testimonials: {
      eyebrow: "Reviews",
      title: "Clients all say the same — first relief, then calm.",
      items: [
        { q: "For three years I didn't know whether I even had to have a waste register. Anna explained it in 20 minutes and took it over.", who: "Magda, hair salon, Kraków" },
        { q: "Environmental inspection — no issues. The paperwork was ready a day ahead.", who: "Tomasz, woodworking shop, 12 people" },
        { q: "Online safety training was a hit — the team did it between shifts, no complaints.", who: "Karolina, HR, manufacturing co. 80 people" },
      ],
    },
    cta: {
      title_pre: "Start with a",
      title_em: "conversation.",
      lead: "Tell me briefly about your scope — I'll prepare a quote and a proposal. I usually reply the same day.",
      button: "Request a quote",
    },
    footer: {
      tag: "Waste · Environment · Safety",
      rights: "© 2026 ECOSAFE. All rights reserved.",
    },

    bdo: {
      eyebrow: "Service 01",
      title_pre: "Waste register —",
      title_em: "so you can sleep.",
      lead: "Registration, records, annual reports, transfer cards. I run it for you, or alongside you — your call.",
      scope_title: "What's included",
      scope: [
        { t: "BDO registration", d: "Full registration in the Polish waste & packaging database (BDO).", price: "299 PLN" },
        { t: "Ongoing records", d: "Waste transfer cards (KPO/KPOK), issued and reconciled so everything adds up.", price: "from 99 PLN / mo" },
        { t: "Data updates", d: "Registry updates when your company changes — address, scope, waste codes.", price: "199 PLN" },
        { t: "Deregistration + report", d: "Full closure of the registry entry with final report.", price: "299 PLN" },
        { t: "Annual waste report", d: "Prepared and filed on time. No March panic.", price: "from 199 PLN" },
        { t: "Personalised BDO training", d: "System training tailored to your company's workflow.", price: "from 599 PLN" },
      ],
      timeline_title: "The year in waste compliance",
      timeline: [
        { m: "January", d: "Wrap up the previous year. Check records are complete.", tag: "Start" },
        { m: "March 15", d: "Report on waste generated in the previous year.", tag: "Deadline" },
        { m: "March 31", d: "Packaging report (if applicable).", tag: "Deadline" },
        { m: "April", d: "Environmental fees — KOBiZE and regional.", tag: "Fees" },
        { m: "Sep–Nov", d: "Typical inspection season. Docs must be current.", tag: "Audits" },
        { m: "December", d: "Close the year, archive, prep reports.", tag: "Wrap-up" },
      ],
    },

    doradztwo: {
      eyebrow: "Service 02",
      title_pre: "Environmental",
      title_em: "advisory.",
      lead: "KOBiZE, packaging, decisions, permits, fees. Everything the law requires — without legalese.",
      scope_title: "Scope",
      scope: [
        { t: "KOBiZE", d: "Emissions database reporting — we establish if you're obliged and prepare the report." },
        { t: "Packaging & EPR", d: "Extended Producer Responsibility. Settlements and recovery organisation contracts." },
        { t: "Permits & decisions", d: "Support in obtaining environmental decisions and sector permits." },
        { t: "Environmental audit", d: "Review of the current state, risk list and a concrete action plan." },
      ],
    },

    bhpPage: {
      eyebrow: "Service 03",
      title_pre: "Online safety",
      title_em: "training.",
      lead: "Fully compliant. No full-day workshops in a conference room. Initial and periodic courses available 24/7.",
      courses_title: "Available courses",
      courses: [
        { t: "Online BHP courses", len: "from 45 min", price: "quote", desc: "Initial and periodic workplace safety courses, available 24/7 — for office staff, managers and manual roles." },
        { t: "Workplace audit", len: "1–3 days", price: "quote", desc: "Comprehensive workstation analysis, hazard identification, review of BHP procedures and document compliance." },
        { t: "Occupational risk assessment", len: "by scope", price: "quote", desc: "Documentation of hazards present at specific workstations." },
        { t: "Initial / periodic training", len: "45 min – 8 hrs", price: "quote", desc: "PDF certificate upon passing. Fully compliant." },
      ],
      how_title: "How it works",
      how: [
        { n: "01", t: "Sign up", d: "Create an account, add your team (or just you)." },
        { n: "02", t: "Take the course", d: "Video + materials + quizzes. You can split it up." },
        { n: "03", t: "Final test", d: "Fair and simple. Pass from 80%." },
        { n: "04", t: "Certificate", d: "Numbered PDF, fully compliant. Emailed immediately." },
      ],
    },

    kontakt: {
      eyebrow: "Contact",
      title_pre: "Write or",
      title_em: "call.",
      lead: "I usually reply the same day. Tell me briefly about your company and scope — I'll prepare a quote and an action plan.",
      form_name: "Name",
      form_email: "Email",
      form_company: "Company (optional)",
      form_topic: "Topic",
      form_topic_opts: ["Waste / BDO", "Environmental advisory", "Safety training", "Something else"],
      form_message: "Message",
      form_submit: "Send message",
      form_success: "Thanks! I'll get back to you within 24 hours.",
      errors: {
        name: "Please enter your name",
        email: "Please enter a valid email",
        message: "Write a few sentences so I know how to help",
      },
      contact_blocks: [
        { t: "Email", v: "kontakt@ecosafe.com.pl" },
        { t: "Phone", v: "+48 791 045 130" },
        { t: "Hours", v: "Mon–Fri · 9:00–17:00" },
        { t: "NIP", v: "6443343386" },
        { t: "REGON", v: "542094091" },
      ],
    },
  },
};

window.COPY = COPY;
