// ECOSAFE — copy (PL / EN)
const COPY = {
  pl: {
    nav: {
      home: "Start",
      bdo: "Kompleksowa obsługa BDO",
      doradztwo: "Doradztwo",
      bhp: "Szkolenia BHP i OŚ",
      about: "O mnie",
      kontakt: "Kontakt",
    },
    hero: {
      eyebrow: "BDO · Ochrona środowiska · BHP",
      title_pre: "Pomagam firmom",
      title_em: "rozumieć",
      title_post: "środowisko i bezpieczeństwo — spokojnie oraz praktycznie.",
      lead: "Misją ECOSAFE jest pomagać ludziom i firmom rozumieć BHP oraz ochronę środowiska w prosty i praktyczny sposób, żeby mogli prowadzić firmy w bezpieczny, świadomy i odpowiedzialny sposób.",
      cta_primary: "Zapytaj o wycenę",
      cta_secondary: "Sprawdź swoją firmę",
      caption: "Dla jednoosobowych działalności, średnich i dużych firm — bez urzędowego tonu.",
    },
    marquee: ["BDO", "Ewidencja odpadów", "Sprawozdania roczne", "BHP online", "Doradztwo", "KOBiZE", "Opakowania", "Audyt środowiskowy"],
    pillars: {
      eyebrow: "Obszary wsparcia",
      title_pre: "Więcej wiedzy,",
      title_em: "więcej spokoju.",
      lead: "Wspieram firmy w obowiązkach BDO, ochrony środowiska i BHP. Profesjonalistów z branży — w rozwoju zawodowym przez ECOSAFE Akademia.",
      firm_eyebrow: "Dla firm",
      firm_os_eyebrow: "Środowisko w Twojej firmie",
      firm_os_lead: "BDO i kompleksowa obsługa środowiskowa — dwa obszary, jedno biuro.",
      firm_bhp_eyebrow: "BHP w Twojej firmie",
      firm_bhp_lead: "Dwa formaty BHP — kursy które kupisz dla pracowników i usługi które wykonuję na miejscu.",
      firm_items: [
        {
          n: "01",
          tag: "BDO",
          title: "Kompleksowa obsługa BDO",
          body: "Prowadzę ewidencję odpadów, pilnuję terminów, przygotowuję sprawozdania roczne i karty przekazania odpadów. Ty zajmujesz się firmą — ja rejestrem.",
          bullets: ["Ewidencja odpadów", "Sprawozdania roczne", "Rejestracja i aktualizacje", "Indywidualne szkolenia z obsługi BDO"],
          route: "bdo",
          img: "pillar-bdo",
        },
        {
          n: "02",
          tag: "Środowisko",
          title: "Obsługa środowiskowa",
          body: "KOBiZE, opłaty środowiskowe, decyzje administracyjne, audyty — wszystko obsłużone w jednym miejscu, bez stresu i opóźnień.",
          bullets: ["KOBiZE i opłaty środowiskowe", "Decyzje i pozwolenia", "Rejestracja i aktualizacje", "Audyty i wdrożenia ulepszeń"],
          route: "doradztwo",
          img: "pillar-doradztwo",
        },
        {
          n: "03",
          tag: "BHP · online",
          title: "Szkolenia BHP online",
          body: "Obowiązkowe szkolenia wstępne i okresowe w platformie ECOSAFE Akademia. Twoja firma kupuje kursy, pracownicy uczą się 24/7.",
          bullets: ["BHP wstępne i okresowe", "Pierwsza pomoc i ppoż.", "Certyfikat zgodny z przepisami", "Dostęp 24/7 przez 12 miesięcy"],
          route: "bhp",
          anchor: "kursy-online",
          img: "pillar-bhp",
        },
        {
          n: "04",
          tag: "BHP · w firmie",
          title: "Obsługa BHP",
          body: "Audyty warunków pracy, ocena ryzyka zawodowego, dokumentacja stanowiskowa i szkolenia stacjonarne — wykonuję u Ciebie w firmie.",
          bullets: ["Audyt warunków pracy", "Ocena ryzyka zawodowego", "Dokumentacja BHP", "Szkolenia stacjonarne"],
          route: "bhp",
          anchor: "obsluga",
          img: "pillar-bhp",
        },
      ],
      pro_eyebrow: "Doskonalenie zawodowe · Akademia Pro",
      pro_lead: "Dla osób z branży BHP i ochrony środowiska — case studies, punkty CPD, webinary live i zamknięta społeczność.",
      pro_items: [
        {
          n: "05",
          tag: "Akademia · BHP Pro",
          title: "Szkolenia BHP dla branży",
          body: "Dla inspektorów, specjalistów BHP i osób w trakcie certyfikacji. Case studies z realnych firm, audyty, soft skills.",
          bullets: ["Zaawansowane kursy z punktami CPD", "Webinary live z Angeliką", "Biblioteka szablonów i list", "Zamknięta społeczność"],
          route: "akademia-bhp",
          theme: "bhp-pro",
        },
        {
          n: "06",
          tag: "Akademia · OŚ Pro",
          title: "Szkolenia z ochrony środowiska dla branży",
          body: "Dla specjalistów OŚ, koordynatorów BDO i audytorów. Praktyczne case studies, procedury i dokumentacja.",
          bullets: ["KOBiZE i sprawozdawczość", "BDO dla zaawansowanych", "Audyty środowiskowe", "Decyzje i pozwolenia"],
          route: "akademia-os",
          theme: "os-pro",
          coming_soon: true,
        },
      ],
    },
    quiz: {
      eyebrow: "3–4 minuty",
      title: "Sprawdź, co Twoja firma powinna mieć w porządku.",
      lead: "7 pytań z zakresu gospodarki odpadami, opakowań i BHP. Na końcu dostajesz diagnozę, listę obowiązków i rekomendowane działania.",
      start: "Zacznij ankietę",
      q: [
        {
          q: "Czy Twoja firma w toku działalności wytwarza odpady inne niż komunalne?",
          hint: "Np. opakowania po surowcach, zużyty sprzęt elektryczny, oleje, tonery, odpady produkcyjne, budowlane, medyczne.",
          opts: ["Tak, regularnie", "Sporadycznie / w niewielkich ilościach", "Nie", "Nie wiem"],
        },
        {
          q: "Czy prowadzisz ewidencję wytwarzanych odpadów w systemie BDO?",
          hint: "Ewidencja obejmuje karty ewidencji odpadów (KEO) oraz karty przekazania odpadów (KPO).",
          opts: ["Tak, na bieżąco", "Prowadzimy, ale z opóźnieniami", "Nie prowadzimy", "Nie wiem, czy nas to dotyczy"],
        },
        {
          q: "Czy wprowadzasz na rynek produkty w opakowaniach lub same opakowania?",
          hint: "Dotyczy producentów, importerów, dystrybutorów pakujących towary we własne opakowania.",
          opts: ["Tak", "Nie", "Nie jestem pewien/pewna"],
        },
        {
          q: "Czy w ostatnim roku składałeś/aś sprawozdanie środowiskowe (BDO, KOBiZE, opłata środowiskowa)?",
          opts: ["Tak, wszystkie wymagane", "Tak, ale nie wszystkie", "Nie składałem/am", "Nie wiem, co mnie dotyczy"],
        },
        {
          q: "Czy szkolenia BHP w Twojej firmie są aktualne?",
          hint: "Szkolenia wstępne dla nowych pracowników oraz okresowe dla pozostałych zatrudnionych.",
          opts: ["Tak, wszyscy pracownicy mają aktualne", "Część osób ma nieaktualne", "Nie mamy aktualnych szkoleń", "Pracuję sam/a"],
        },
        {
          q: "Czy wiesz, jakie obowiązki BHP dotyczą Twojej działalności?",
          hint: "Np. ocena ryzyka zawodowego, instrukcje stanowiskowe, badania lekarskie, środki ochrony indywidualnej.",
          opts: ["Tak, mam pełną dokumentację", "Znam część, reszta wymaga uporządkowania", "Nie — potrzebuję wsparcia", "Nie dotyczy mojej działalności"],
        },
        {
          q: "Kiedy ostatnio firma przechodziła kontrolę (WIOŚ, PIP, sanepid)?",
          opts: ["W ostatnim roku — bez uwag", "W ostatnim roku — z uwagami", "Ponad rok temu", "Nigdy nie było kontroli"],
        },
      ],
      result_title: "Wynik diagnozy:",
      risk_label: "Poziom ryzyka",
      risk_low: "Niski",
      risk_mid: "Średni",
      risk_high: "Wysoki",
      duties_label: "Prawdopodobne obowiązki",
      services_label: "Rekomendowane usługi ECOSAFE",
      again: "Wypełnij jeszcze raz",
      book: "Zapytaj o wycenę",
    },
    about: {
      eyebrow: "Kto za tym stoi",
      name: "Angelika Siołek",
      role: "Specjalistka BHP i ochrony środowiska",
      body_1: "Prowadzę ECOSAFE, ponieważ wiele firm nie potrzebuje teorii i pięknie opisanych procedur, ale uporządkowanego wsparcia, które jasno pokazuje, jakie działania należy podjąć, DLACZEGO należy je podjąć, w jakiej kolejności i w jakich terminach. I przede wszystkim - jaki ma to realny wpływ na przedsiębiorstwo.",
      body_2: "Pomagam firmom rozsądnie wykorzystywać zasoby naturalne, tak aby przy tym samym poziomie produkcji mogły działać efektywniej i wdrażać realne oszczędności. Wierzę, że odpowiedzialne podejście do środowiska nie wyklucza rozwoju firmy — przeciwnie, może wspierać jej stabilność, przewidywalność i lepsze decyzje na przyszłość.",
      stats: [
        { n: "500+", label: "wykonanych sprawozdań" },
        { n: "12", label: "lat doświadczenia" },
        { n: "0", label: "kar po kontroli" },
      ],
    },
    testimonials: {
      eyebrow: "Doświadczenie",
      title: "Moje wykształcenie i rozwój, które pracują na rzecz Twojej firmy.",
      education_title: "Wykształcenie",
      education: [
        { year: "2022", school: "Centralna Szkoła Państwowej Straży Pożarnej w Częstochowie", detail: "Inspektor ochrony przeciwpożarowej" },
        { year: "2020 – 2021", school: "Wyższa Szkoła Zarządzania Ochroną Pracy w Katowicach", detail: "Magister · specjalność: Europejski Menedżer BHP" },
        { year: "2019 – 2020", school: "Politechnika Śląska w Gliwicach", detail: "Studia podyplomowe · Mechanika i Budowa Maszyn — Projektowanie Maszyn Specjalnych" },
        { year: "2011 – 2012", school: "Politechnika Śląska w Gliwicach", detail: "Magister · Inżynieria Środowiska i Energetyki — Technologia wody, ścieków i gospodarka odpadami" },
        { year: "2007 – 2011", school: "Politechnika Śląska w Gliwicach", detail: "Inżynier · Inżynieria Środowiska i Energetyki — Czyste technologie w energetyce i motoryzacji" },
      ],
      courses_title: "Kursy i certyfikaty",
      courses: [
        "Certyfikat auditora wewnętrznego Systemu Zarządzania BHP wg normy PN-ISO 45001:2018",
        "Certyfikat Auditora Zintegrowanego Systemu Zarządzania wg norm ISO 9001:2015 i ISO 14001:2015",
        "Kurs „Maksymalna Produktywność”",
        "Kurs „Asertywność w pracy”",
      ],
    },
    cta: {
      title_pre: "Zacznijmy od",
      title_em: "rozmowy.",
      lead: "Opisz krótko swój zakres — przygotuję wycenę i propozycję współpracy. Zazwyczaj odpowiadam tego samego dnia.",
      button: "Zapytaj o wycenę",
    },
    footer: {
      tag: "BDO · Ochrona środowiska · BHP",
      rights: "© 2026 ECOSAFE. Wszystkie prawa zastrzeżone.",
    },

    // BDO page
    bdo: {
      eyebrow: "Usługa 01",
      title_pre: "BDO —",
      title_em: "ja się tym zajmę.",
      lead: "Rejestr, ewidencja, sprawozdania, KPO. Poprowadzę to za Ciebie.",
      scope_title: "Co obejmuje obsługa",
      scope: [
        { t: "Rejestracja w BDO", d: "Pełna rejestracja podmiotu w Bazie danych o produktach i opakowaniach oraz o gospodarce odpadami.", price: "299 zł" },
        { t: "Prowadzenie ewidencji", d: "Bieżąca ewidencja odpadów, KPO, KPOK. Wystawianie i pilnowanie, żeby wszystko się zgadzało.", price: "od 99 zł / mies." },
        { t: "Aktualizacja danych", d: "Aktualizacja wpisu w BDO przy zmianach w firmie — adres, zakres działalności, odpady.", price: "199 zł" },
        { t: "Wykreślenie z BDO + sprawozdanie", d: "Kompleksowe zamknięcie rejestru wraz z końcowym sprawozdaniem.", price: "299 zł" },
        { t: "Sprawozdanie odpadowe", d: "Przygotowanie i złożenie rocznego sprawozdania w terminie. ", price: "od 199 zł" },
        { t: "Indywidualne szkolenie BDO", d: "Szkolenie z obsługi systemu BDO dostosowane do Twojej firmy.", price: "od 599 zł" },
      ],
      timeline_title: "Kalendarz obowiązków — rok w BDO",
      timeline: [
        { m: "28 luty ", d: "Złożenie przez każdy podmiot korzystający ze środowiska raportu do KOBIZE", tag: "Start" },
        { m: "15 marca", d: "Sprawozdanie o odpadach", tag: "Deadline" },
        { m: "15 marca", d: "Sprawozdanie o opakowaniach ", tag: "Deadline" },
        { m: "31 marca", d: "Opłaty środowiskowe do marszałka", tag: "Opłaty" },
        { m: "Wrzesień–listopad", d: "Typowy sezon kontroli WIOŚ. Dokumenty muszą być na bieżąco", tag: "Kontrole" },
        { m: "Grudzień", d: "Domknięcie roku, archiwizacja, przygotowanie do sprawozdań", tag: "Domknięcie" },
      ],
    },

    doradztwo: {
      eyebrow: "Usługa 02",
      title_pre: "Doradztwo",
      title_em: "środowiskowe.",
      lead: "KOBiZE, opakowania, decyzje, pozwolenia, opłaty. Wszystko, czego wymaga prawo — bez prawniczego bełkotu.",
      scope_title: "Zakres doradztwa",
      scope: [
        { t: "KOBiZE", d: "Raport do Krajowej bazy o emisjach — ustalenie, czy jesteś zobowiązany i przygotowanie raportu." },
        { t: "Opakowania i ROP", d: "Rozszerzona odpowiedzialność producenta. Rozliczenia, umowy z organizacją odzysku." },
        { t: "Pozwolenia i decyzje", d: "Wsparcie w uzyskiwaniu decyzji środowiskowych i pozwoleń sektorowych." },
        { t: "Audyt środowiskowy", d: "Przegląd obecnej sytuacji firmy, lista ryzyk i konkretny plan działań." },
      ],
    },

    bhpPage: {
      eyebrow: "Szkolenia BHP i ochrona środowiska",
      title_pre: "Szkolenia BHP",
      title_em: "online i u Ciebie w firmie.",
      lead: "Pełna oferta szkoleń — od kursów wstępnych dostępnych 24/7 w naszej Akademii, po audyty i warsztaty stacjonarne w Twojej firmie. Wszystko zgodne z przepisami.",

      online_eyebrow: "Część 1 · ECOSAFE Akademia",
      online_title: "Kursy online — uczysz się we własnym tempie",
      online_sub: "Dwie ścieżki: obowiązkowe kursy dla pracowników oraz rozwojowe dla profesjonalistów BHP. Wszystko w platformie ECOSAFE Akademia — dostęp 24/7 przez 12 miesięcy.",
      online_cta: "Kup w Akademii",
      online_all_cta: "Zobacz wszystkie kursy w Akademii",

      required_eyebrow: "Dla firm i pracowników",
      required_title: "Obowiązkowe — wymagane przepisami",
      required_sub: "Wstępne i okresowe szkolenia BHP zgodne z rozporządzeniem MGiP. Certyfikat PDF od razu po zdanym teście.",
      online_required: [
        { id: "bhp-wstepne", t: "BHP wstępne", len: "1 godz 20 min", price: "89 zł", tag: "Najpopularniejszy", desc: "Obowiązkowe szkolenie wstępne dla każdego nowego pracownika. Zgodne z rozporządzeniem MGiP." },
        { id: "bhp-biuro", t: "BHP okresowe — biuro", len: "2 godz", price: "129 zł", desc: "Okresowe szkolenie BHP dla pracowników biurowych. Wymagane co 5 lat." },
        { id: "bhp-fizyczni", t: "BHP okresowe — pracownicy fizyczni", len: "3 godz", price: "149 zł", desc: "Dla stanowisk robotniczych z elementami praktycznymi. Materiały do pobrania." },
        { id: "bhp-kadra", t: "BHP dla kadry kierowniczej", len: "4 godz", price: "249 zł", desc: "Pełna odpowiedzialność pracodawcy. Dokumentacja, postępowanie po wypadku, kontrole PIP." },
        { id: "pierwsza-pomoc", t: "Pierwsza pomoc przedmedyczna", len: "2 godz 30 min", price: "159 zł", tag: "Nowy", desc: "Reanimacja, AED, postępowanie z osobą nieprzytomną — z filmami pokazowymi." },
        { id: "ppoz", t: "Ochrona przeciwpożarowa", len: "1 godz 45 min", price: "119 zł", desc: "Zasady postępowania w razie pożaru, ewakuacja, oznakowanie, użycie gaśnic." },
      ],

      pro_eyebrow: "Dla profesjonalistów BHP",
      pro_title: "Rozwojowe — Akademia Pro",
      pro_sub: "Dla inspektorów, specjalistów BHP i osób w trakcie certyfikacji. Case studies, audyty, punkty CPD, webinary live i zamknięta społeczność.",
      pro_cta: "Wejdź do Akademii Pro",
      online_pro: [
        { id: "pro-ocena-ryzyka", t: "Ocena ryzyka zawodowego — case studies", len: "8 godz · 8 CPD", price: "599 zł", desc: "5 realnych case studies z różnych branż. Krok po kroku — od zbierania danych po dokumentację gotową do PIP." },
        { id: "pro-audyt", t: "Audyt BHP w firmie produkcyjnej", len: "10 godz · 10 CPD", price: "749 zł", desc: "Krok po kroku — od planu audytu, przez wywiady, po raport końcowy z rekomendacjami." },
        { id: "pro-komunikacja", t: "Jak prowadzić szkolenia BHP, których ludzie słuchają", len: "6 godz · 6 CPD", price: "449 zł", desc: "Storytelling, prowadzenie warsztatów, radzenie sobie z oporem zespołu. Soft skills dla trenerów BHP." },
      ],

      onsite_eyebrow: "Część 2 · Usługi w Twojej firmie",
      onsite_title: "Czego nie zrobisz online — robimy u Ciebie",
      onsite_sub: "Audyty, dokumentacja stanowiskowa i szkolenia stacjonarne dla zespołu. Realizuję u Ciebie w firmie — w Polsce, na miejscu.",
      onsite_cta: "Zapytaj o ofertę",
      onsite_services: [
        { t: "Audyt warunków pracy", len: "1–3 dni", desc: "Kompleksowa analiza stanowisk pracy, identyfikacja zagrożeń, ocena procedur BHP i spójności dokumentacji z prawem. Raport z rekomendacjami." },
        { t: "Ocena ryzyka zawodowego", len: "wg zakresu", desc: "Sporządzenie dokumentacji oceny ryzyka dla wszystkich stanowisk w firmie. Aktualizacja co rok lub po zmianach." },
        { t: "Szkolenia BHP stacjonarne", len: "wg zakresu", desc: "Warsztaty na żywo dla zespołu — w Twojej siedzibie. Program dopasowany do branży i specyfiki firmy." },
      ],

      how_title: "Jak działa kurs online",
      how: [
        { n: "01", t: "Rejestracja", d: "Zakładasz konto, dodajesz pracowników (lub siebie)." },
        { n: "02", t: "Kurs online", d: "Wideo + materiały + quizy. Można w kilku podejściach." },
        { n: "03", t: "Test końcowy", d: "Prosty, rzetelny. Zaliczenie od 80%." },
        { n: "04", t: "Certyfikat", d: "PDF z numerem, zgodny z przepisami. Natychmiast na mailu." },
      ],
    },

    akademiaBhp: {
      eyebrow: "Akademia · BHP Pro",
      title_pre: "Rozwijaj się",
      title_em: "w zawodzie BHP.",
      lead: "Dla inspektorów, specjalistów BHP i osób w trakcie certyfikacji. Case studies z realnych firm, punkty CPD, webinary live i zamknięta społeczność — wszystko w ścieżce Pro w ECOSAFE Akademia.",
      courses_eyebrow: "Część 1 · Kursy zaawansowane",
      courses_title: "Co znajdziesz w Akademii BHP Pro",
      courses_sub: "Jednorazowy zakup kursu, dostęp na 12 miesięcy, materiały na zawsze. Każdy kurs kończy się punktami CPD i certyfikatem zaliczenia.",
      cta: "Kup w Akademii Pro",
      all_cta: "Wejdź do Akademii BHP Pro",
      courses: [
        { id: "pro-ocena-ryzyka", t: "Ocena ryzyka zawodowego — case studies", len: "8 godz · 8 CPD", price: "599 zł", desc: "5 realnych case studies z różnych branż. Krok po kroku — od zbierania danych po dokumentację gotową do PIP." },
        { id: "pro-audyt", t: "Audyt BHP w firmie produkcyjnej", len: "10 godz · 10 CPD", price: "749 zł", desc: "Krok po kroku — od planu audytu, przez wywiady, po raport końcowy z rekomendacjami." },
        { id: "pro-komunikacja", t: "Jak prowadzić szkolenia BHP, których ludzie słuchają", len: "6 godz · 6 CPD", price: "449 zł", desc: "Storytelling, prowadzenie warsztatów, radzenie sobie z oporem zespołu. Soft skills dla trenerów BHP." },
      ],
      features_eyebrow: "Część 2 · Nie tylko kursy",
      features_title: "Co jeszcze masz jako Pro",
      features_sub: "Akademia Pro to społeczność i ciągły rozwój zawodowy — nie tylko same kupione kursy.",
      features: [
        { t: "Webinary live", d: "Co miesiąc spotkanie z Angeliką + sesja Q&A. Nagrania dostępne w bibliotece." },
        { t: "Społeczność BHP", d: "Zamknięte forum dla profesjonalistów. Wymiana case studies, pytania, dyskusje." },
        { t: "Biblioteka materiałów", d: "Szablony oceny ryzyka, listy kontrolne, instrukcje stanowiskowe — gotowe do edycji." },
        { t: "Certyfikat BHP Pro", d: "Egzamin końcowy i zaświadczenie o uczestnictwie w programie rozwojowym." },
      ],
    },

    akademiaOs: {
      eyebrow: "Akademia · OŚ Pro · Wkrótce",
      title_pre: "Rozwijaj się w",
      title_em: "ochronie środowiska.",
      lead: "Dla specjalistów ds. ochrony środowiska, koordynatorów BDO i audytorów. Trwają prace nad pierwszymi kursami — zostaw kontakt, dam znać jak ruszamy.",
      coming_soon_label: "Program w przygotowaniu — premiera 2026",
      courses_eyebrow: "Część 1 · Planowane kursy",
      courses_title: "Co znajdziesz w Akademii OŚ Pro",
      courses_sub: "Cztery kursy zaawansowane w przygotowaniu. Cel — to samo doświadczenie co BHP Pro, tylko skupione na ochronie środowiska.",
      cta: "Wkrótce",
      all_cta: "Zostaw kontakt — wczesny dostęp",
      courses: [
        { id: "os-kobize", t: "KOBiZE — sprawozdawczość case studies", len: "8 godz · 8 CPD", price: "wkrótce", desc: "Pełen cykl rocznej sprawozdawczości KOBiZE krok po kroku z realnymi przykładami z różnych branż." },
        { id: "os-bdo-pro", t: "BDO dla zaawansowanych", len: "10 godz · 10 CPD", price: "wkrótce", desc: "Złożone ewidencje, transgraniczne przemieszczenie odpadów, kontrole IOŚ — wszystko od kuchni." },
        { id: "os-audyt", t: "Audyt środowiskowy w firmie", len: "8 godz · 8 CPD", price: "wkrótce", desc: "Krok po kroku — od planu audytu do raportu z rekomendacjami i planem działań." },
        { id: "os-decyzje", t: "Decyzje i pozwolenia środowiskowe", len: "6 godz · 6 CPD", price: "wkrótce", desc: "Wniosek, postępowanie, terminy, odwołania. Praktyczne przykłady z administracyjnej kuchni." },
      ],
      features_eyebrow: "Część 2 · Pakiet Pro OŚ",
      features_title: "Co dostaniesz",
      features_sub: "Trwa projektowanie programu. Cel — kompletne wsparcie zawodowe dla osób z branży ochrony środowiska.",
      features: [
        { t: "Webinary live", d: "Spotkania z ekspertem co miesiąc + sesje Q&A. Nagrania w bibliotece." },
        { t: "Społeczność OŚ", d: "Zamknięte forum dla specjalistów ochrony środowiska." },
        { t: "Biblioteka materiałów", d: "Szablony wniosków, list kontrolnych, procedur — gotowe do użycia." },
        { t: "Certyfikat OŚ Pro", d: "Egzamin końcowy i zaświadczenie o uczestnictwie w programie." },
      ],
    },

    kontakt: {
      eyebrow: "Kontakt",
      title_pre: "Napisz albo",
      title_em: "zadzwoń.",
      lead: "Najczęściej odpowiadam tego samego dnia. Opisz krótko firmę i zakres — przygotuję wycenę i plan działań.",
      form_name: "Imię",
      form_email: "Email",
      form_company: "Firma (opcjonalnie)",
      form_topic: "Temat",
      form_topic_opts: ["BDO", "Doradztwo środowiskowe", "Szkolenia BHP", "Coś innego"],
      form_message: "Wiadomość",
      form_submit: "Wyślij wiadomość",
      form_success: "Dzięki! Odezwę się w ciągu 24 godzin.",
      errors: {
        name: "Podaj imię",
        email: "Podaj poprawny email",
        message: "Napisz kilka zdań, żebym wiedziała, z czym pomóc",
      },
      contact_blocks: [
        { t: "Email", v: "kontakt@ecosafe.com.pl" },
        { t: "Telefon", v: "+48 791 045 130" },
        { t: "Godziny", v: "Pn–Pt · 9:00–17:00" },
        { t: "NIP", v: "6443343386" },
        { t: "REGON", v: "542094091" },
      ],
    },
  },

  en: {
    nav: {
      home: "Home",
      bdo: "Waste (BDO)",
      doradztwo: "Advisory",
      bhp: "Safety training",
      about: "About",
      kontakt: "Contact",
    },
    hero: {
      eyebrow: "Waste · Environment · Workplace safety",
      title_pre: "I help businesses",
      title_em: "understand",
      title_post: "environment and safety — simply.",
      lead: "ECOSAFE's mission is to help people and companies understand workplace safety and environmental protection in a simple, practical way — so they can act safer, more consciously and more responsibly.",
      cta_primary: "Request a quote",
      cta_secondary: "Check your company",
      caption: "For sole traders, mid-size and large companies — no bureaucratic tone.",
    },
    marquee: ["Waste register", "BDO", "Annual reports", "Online safety training", "Advisory", "KOBiZE", "Packaging", "Environmental audit"],
    pillars: {
      eyebrow: "Areas of support",
      title_pre: "Less panic,",
      title_em: "more sense.",
      lead: "I support companies with their waste, environmental and safety obligations — and safety professionals with their career development through the ECOSAFE Academy.",
      firm_eyebrow: "For companies",
      firm_os_eyebrow: "Environment at your company",
      firm_os_lead: "BDO records and full environmental services — two areas, one desk.",
      firm_bhp_eyebrow: "Safety at your company",
      firm_bhp_lead: "Two safety formats — courses your team takes, plus services I deliver on-site.",
      firm_items: [
        {
          n: "01",
          tag: "Waste",
          title: "BDO — waste register",
          body: "I keep your waste records, watch the deadlines, prepare annual reports and waste transfer cards. You run the business — I run the register.",
          bullets: ["Records & transfer cards", "Annual reports", "Registration & updates", "Inspection support"],
          route: "bdo",
          img: "pillar-bdo",
        },
        {
          n: "02",
          tag: "Environment",
          title: "Environmental services",
          body: "KOBiZE, environmental fees, administrative decisions, audits — handled in one place, without stress or delays.",
          bullets: ["KOBiZE & fees", "Decisions & permits", "Packaging & EPR", "Audits & rollouts"],
          route: "doradztwo",
          img: "pillar-doradztwo",
        },
        {
          n: "03",
          tag: "Safety · online",
          title: "Online safety training",
          body: "Mandatory initial and periodic training in the ECOSAFE Academy. Your company buys the courses, employees learn 24/7.",
          bullets: ["Initial & periodic", "First aid & fire safety", "Compliant PDF certificate", "24/7 access for 12 months"],
          route: "bhp",
          anchor: "kursy-online",
          img: "pillar-bhp",
        },
        {
          n: "04",
          tag: "Safety · on-site",
          title: "On-site safety services",
          body: "Workplace audits, occupational risk assessments, workstation documentation and live training — delivered at your premises.",
          bullets: ["Workplace audits", "Risk assessment", "Safety documentation", "On-site training"],
          route: "bhp",
          anchor: "obsluga",
          img: "pillar-bhp",
        },
      ],
      pro_eyebrow: "Professional development · Academy Pro",
      pro_lead: "For safety and environmental specialists — case studies, CPD credits, live webinars and a private community.",
      pro_items: [
        {
          n: "05",
          tag: "Academy · Safety Pro",
          title: "Safety training for the industry",
          body: "For inspectors, safety specialists and people pursuing certification. Real case studies, audits, soft skills.",
          bullets: ["Advanced CPD-credited courses", "Live webinars with Angelika", "Template & checklist library", "Private community"],
          route: "akademia-bhp",
          theme: "bhp-pro",
        },
        {
          n: "06",
          tag: "Academy · Environment Pro",
          title: "Environmental training for the industry",
          body: "For environmental specialists, BDO coordinators and auditors. Practical case studies, procedures, documentation.",
          bullets: ["KOBiZE & reporting", "Advanced BDO", "Environmental audits", "Permits & decisions"],
          route: "akademia-os",
          theme: "os-pro",
          coming_soon: true,
        },
      ],
    },
    quiz: {
      eyebrow: "3–4 minutes",
      title: "Check what your company should have in order.",
      lead: "7 questions on waste, packaging and workplace safety. At the end you get a diagnosis, a list of duties and recommended next steps.",
      start: "Start the survey",
      q: [
        {
          q: "Does your company generate waste other than municipal?",
          hint: "E.g. packaging, used electronics, oils, toners, production/construction/medical waste.",
          opts: ["Yes, regularly", "Occasionally / small amounts", "No", "Not sure"],
        },
        {
          q: "Do you keep waste records in the BDO system?",
          hint: "Waste records include KEO cards and KPO transfer cards.",
          opts: ["Yes, up to date", "Yes, but with delays", "No, we don't", "Unsure if it applies"],
        },
        {
          q: "Do you place products in packaging on the market, or packaging itself?",
          hint: "Applies to producers, importers and distributors packing goods in their own packaging.",
          opts: ["Yes", "No", "Not sure"],
        },
        {
          q: "Did you file required environmental reports in the last year (BDO, KOBiZE, environmental fee)?",
          opts: ["Yes, all of them", "Yes, but not all", "I did not file", "Unsure what applies"],
        },
        {
          q: "Is your team's safety training up to date?",
          hint: "Initial training for new hires and periodic training for the rest.",
          opts: ["Yes, everyone is current", "Some are out of date", "No, none are current", "I work alone"],
        },
        {
          q: "Do you know which workplace safety obligations apply to your business?",
          hint: "E.g. risk assessment, workstation instructions, medical checks, PPE.",
          opts: ["Yes, full documentation", "Partial — needs tidying", "No — I need help", "Doesn't apply to me"],
        },
        {
          q: "When was your company last inspected (environmental, labour, sanitary)?",
          opts: ["In the last year — no findings", "In the last year — with findings", "Over a year ago", "Never"],
        },
      ],
      result_title: "Diagnosis:",
      risk_label: "Risk level",
      risk_low: "Low",
      risk_mid: "Medium",
      risk_high: "High",
      duties_label: "Likely obligations",
      services_label: "Recommended ECOSAFE services",
      again: "Take it again",
      book: "Request a quote",
    },
    about: {
      eyebrow: "Who's behind it",
      name: "Angelika Siołek",
      role: "Safety & environment specialist",
      body_1: "I run ECOSAFE because I noticed that businesses don't need another regulation to read — they need someone to say: „do this, then this, then this, by this date\".",
      body_2: "I take care that natural resources are used sensibly — so they can serve not only us, but our children and future generations. Because a clean future starts with conscious decisions made today.",
      stats: [
        { n: "120+", label: "companies supported" },
        { n: "8", label: "years of experience" },
        { n: "0", label: "fines post-inspection" },
      ],
    },
    testimonials: {
      eyebrow: "Experience",
      title: "Education, postgraduate studies and courses — where the expertise comes from.",
      education_title: "Education",
      education: [
        { year: "2022", school: "Central School of the State Fire Service in Częstochowa", detail: "Fire safety inspector" },
        { year: "2020 – 2021", school: "University of Occupational Safety Management in Katowice", detail: "Master's · European OHS Manager" },
        { year: "2019 – 2020", school: "Silesian University of Technology, Gliwice", detail: "Postgraduate · Mechanical Engineering — Design of Special Machines" },
        { year: "2011 – 2012", school: "Silesian University of Technology, Gliwice", detail: "Master's · Environmental Engineering — Water, Wastewater & Waste Management" },
        { year: "2007 – 2011", school: "Silesian University of Technology, Gliwice", detail: "Engineer's · Environmental Engineering — Clean technologies in energy and automotive" },
      ],
      courses_title: "Courses & certificates",
      courses: [
        "Internal auditor of OHS Management System per PN-ISO 45001:2018",
        "Auditor of Integrated Management System per ISO 9001:2015 and ISO 14001:2015",
        "“Maximum Productivity” course",
        "“Assertiveness at work” course",
      ],
    },
    cta: {
      title_pre: "Start with a",
      title_em: "conversation.",
      lead: "Tell me briefly about your scope — I'll prepare a quote and a proposal. I usually reply the same day.",
      button: "Request a quote",
    },
    footer: {
      tag: "Waste · Environment · Safety",
      rights: "© 2026 ECOSAFE. All rights reserved.",
    },

    bdo: {
      eyebrow: "Service 01",
      title_pre: "Waste register —",
      title_em: "so you can sleep.",
      lead: "Registration, records, annual reports, transfer cards. I run it for you, or alongside you — your call.",
      scope_title: "What's included",
      scope: [
        { t: "BDO registration", d: "Full registration in the Polish waste & packaging database (BDO).", price: "299 PLN" },
        { t: "Ongoing records", d: "Waste transfer cards (KPO/KPOK), issued and reconciled so everything adds up.", price: "from 99 PLN / mo" },
        { t: "Data updates", d: "Registry updates when your company changes — address, scope, waste codes.", price: "199 PLN" },
        { t: "Deregistration + report", d: "Full closure of the registry entry with final report.", price: "299 PLN" },
        { t: "Annual waste report", d: "Prepared and filed on time. No March panic.", price: "from 199 PLN" },
        { t: "Personalised BDO training", d: "System training tailored to your company's workflow.", price: "from 599 PLN" },
      ],
      timeline_title: "The year in waste compliance",
      timeline: [
        { m: "January", d: "Wrap up the previous year. Check records are complete.", tag: "Start" },
        { m: "March 15", d: "Report on waste generated in the previous year.", tag: "Deadline" },
        { m: "March 31", d: "Packaging report (if applicable).", tag: "Deadline" },
        { m: "April", d: "Environmental fees — KOBiZE and regional.", tag: "Fees" },
        { m: "Sep–Nov", d: "Typical inspection season. Docs must be current.", tag: "Audits" },
        { m: "December", d: "Close the year, archive, prep reports.", tag: "Wrap-up" },
      ],
    },

    doradztwo: {
      eyebrow: "Service 02",
      title_pre: "Environmental",
      title_em: "advisory.",
      lead: "KOBiZE, packaging, decisions, permits, fees. Everything the law requires — without legalese.",
      scope_title: "Scope",
      scope: [
        { t: "KOBiZE", d: "Emissions database reporting — we establish if you're obliged and prepare the report." },
        { t: "Packaging & EPR", d: "Extended Producer Responsibility. Settlements and recovery organisation contracts." },
        { t: "Permits & decisions", d: "Support in obtaining environmental decisions and sector permits." },
        { t: "Environmental audit", d: "Review of the current state, risk list and a concrete action plan." },
      ],
    },

    bhpPage: {
      eyebrow: "Safety training & environmental services",
      title_pre: "Safety training",
      title_em: "online and on-site.",
      lead: "Full offering — from on-demand courses available 24/7 in our Academy, to on-site audits and live workshops at your premises. All fully compliant.",

      online_eyebrow: "Part 1 · ECOSAFE Academy",
      online_title: "Online courses — learn at your own pace",
      online_sub: "Two tracks: mandatory courses for employees, and a development path for safety professionals. All in the ECOSAFE Academy — 24/7 access for 12 months.",
      online_cta: "Buy in the Academy",
      online_all_cta: "See all courses in the Academy",

      required_eyebrow: "For companies & employees",
      required_title: "Mandatory — required by law",
      required_sub: "Initial and periodic safety training compliant with the MGiP regulation. PDF certificate immediately after passing the test.",
      online_required: [
        { id: "bhp-wstepne", t: "Initial safety training", len: "1h 20min", price: "89 zł", tag: "Most popular", desc: "Mandatory onboarding training for every new employee. Compliant with the MGiP regulation." },
        { id: "bhp-biuro", t: "Periodic — office staff", len: "2h", price: "129 zł", desc: "Periodic safety training for office workers. Required every 5 years." },
        { id: "bhp-fizyczni", t: "Periodic — manual roles", len: "3h", price: "149 zł", desc: "For manual workstations with practical elements. Downloadable materials." },
        { id: "bhp-kadra", t: "Safety for managers", len: "4h", price: "249 zł", desc: "Full employer responsibility. Documentation, post-incident procedures, PIP inspections." },
        { id: "pierwsza-pomoc", t: "First aid", len: "2h 30min", price: "159 zł", tag: "New", desc: "CPR, AED, handling unconscious persons — with demonstration videos." },
        { id: "ppoz", t: "Fire safety", len: "1h 45min", price: "119 zł", desc: "Fire response, evacuation, signage, extinguisher use." },
      ],

      pro_eyebrow: "For safety professionals",
      pro_title: "Development — Academy Pro",
      pro_sub: "For inspectors, safety specialists and people pursuing certification. Case studies, audits, CPD credits, live webinars and a private community.",
      pro_cta: "Enter Academy Pro",
      online_pro: [
        { id: "pro-ocena-ryzyka", t: "Occupational risk — case studies", len: "8h · 8 CPD", price: "599 zł", desc: "5 real case studies from different industries. Step by step — from data collection to PIP-ready documentation." },
        { id: "pro-audyt", t: "Safety audit in a production company", len: "10h · 10 CPD", price: "749 zł", desc: "Step by step — from the audit plan, through interviews, to the final report with recommendations." },
        { id: "pro-komunikacja", t: "Running safety training people actually listen to", len: "6h · 6 CPD", price: "449 zł", desc: "Storytelling, facilitation, dealing with team resistance. Soft skills for safety trainers." },
      ],

      onsite_eyebrow: "Part 2 · Services at your company",
      onsite_title: "What you can't do online — we do on-site",
      onsite_sub: "Audits, workstation documentation and live training for your team. Delivered at your premises across Poland.",
      onsite_cta: "Request a quote",
      onsite_services: [
        { t: "Workplace audit", len: "1–3 days", desc: "Comprehensive workstation analysis, hazard identification, review of safety procedures and document compliance. Report with recommendations." },
        { t: "Occupational risk assessment", len: "by scope", desc: "Risk assessment documentation for every workstation. Updated yearly or after changes." },
        { t: "On-site safety training", len: "by scope", desc: "Live workshops for your team — at your premises. Program tailored to your industry and company." },
      ],

      how_title: "How an online course works",
      how: [
        { n: "01", t: "Sign up", d: "Create an account, add your team (or just you)." },
        { n: "02", t: "Take the course", d: "Video + materials + quizzes. You can split it up." },
        { n: "03", t: "Final test", d: "Fair and simple. Pass from 80%." },
        { n: "04", t: "Certificate", d: "Numbered PDF, fully compliant. Emailed immediately." },
      ],
    },

    akademiaBhp: {
      eyebrow: "Academy · Safety Pro",
      title_pre: "Grow your career",
      title_em: "in safety.",
      lead: "For inspectors, safety specialists and people pursuing certification. Real case studies, CPD credits, live webinars and a private community — the Pro track in the ECOSAFE Academy.",
      courses_eyebrow: "Part 1 · Advanced courses",
      courses_title: "What you'll find in Safety Pro",
      courses_sub: "One-time purchase, 12 months of access, materials forever. Every course ends with CPD credits and a completion certificate.",
      cta: "Buy in Academy Pro",
      all_cta: "Enter Safety Pro",
      courses: [
        { id: "pro-ocena-ryzyka", t: "Risk assessment — case studies", len: "8h · 8 CPD", price: "599 zł", desc: "5 real case studies across industries. Step by step — from data collection to PIP-ready documentation." },
        { id: "pro-audyt", t: "Safety audit in a production company", len: "10h · 10 CPD", price: "749 zł", desc: "Step by step — from the audit plan, through interviews, to the final report with recommendations." },
        { id: "pro-komunikacja", t: "Running training people actually listen to", len: "6h · 6 CPD", price: "449 zł", desc: "Storytelling, facilitation, dealing with resistance. Soft skills for safety trainers." },
      ],
      features_eyebrow: "Part 2 · More than courses",
      features_title: "What else you get as Pro",
      features_sub: "Academy Pro is a community and ongoing professional growth — not just bought courses.",
      features: [
        { t: "Live webinars", d: "Monthly meeting with Angelika + Q&A. Recordings available." },
        { t: "Safety community", d: "Private forum for professionals. Case studies, questions, discussions." },
        { t: "Material library", d: "Risk assessment templates, checklists, work instructions — ready to edit." },
        { t: "Safety Pro certificate", d: "Final exam and a completion certificate." },
      ],
    },

    akademiaOs: {
      eyebrow: "Academy · Environment Pro · Coming soon",
      title_pre: "Grow your career in",
      title_em: "environmental protection.",
      lead: "For environmental specialists, BDO coordinators and auditors. We're building the first courses — leave your details and I'll let you know when we launch.",
      coming_soon_label: "Program in preparation — launch 2026",
      courses_eyebrow: "Part 1 · Planned courses",
      courses_title: "What you'll find in Environment Pro",
      courses_sub: "Four advanced courses in preparation. Same experience as Safety Pro, but focused on environmental protection.",
      cta: "Coming soon",
      all_cta: "Get early access",
      courses: [
        { id: "os-kobize", t: "KOBiZE — reporting case studies", len: "8h · 8 CPD", price: "soon", desc: "The full annual KOBiZE reporting cycle, step by step, with real examples from different industries." },
        { id: "os-bdo-pro", t: "Advanced BDO", len: "10h · 10 CPD", price: "soon", desc: "Complex records, transboundary waste, IOŚ inspections — all the messy details." },
        { id: "os-audyt", t: "Environmental audit at a company", len: "8h · 8 CPD", price: "soon", desc: "Step by step — from audit plan to a final report with recommendations and an action plan." },
        { id: "os-decyzje", t: "Environmental decisions & permits", len: "6h · 6 CPD", price: "soon", desc: "Application, proceedings, deadlines, appeals. Practical examples from the administrative side." },
      ],
      features_eyebrow: "Part 2 · The Pro package",
      features_title: "What you'll get",
      features_sub: "Program design in progress. The goal — complete professional support for environmental specialists.",
      features: [
        { t: "Live webinars", d: "Monthly expert sessions + Q&A. Recordings in the library." },
        { t: "Environment community", d: "Private forum for environmental specialists." },
        { t: "Material library", d: "Application templates, checklists, procedures — ready to use." },
        { t: "Environment Pro certificate", d: "Final exam and a completion certificate." },
      ],
    },

    kontakt: {
      eyebrow: "Contact",
      title_pre: "Write or",
      title_em: "call.",
      lead: "I usually reply the same day. Tell me briefly about your company and scope — I'll prepare a quote and an action plan.",
      form_name: "Name",
      form_email: "Email",
      form_company: "Company (optional)",
      form_topic: "Topic",
      form_topic_opts: ["Waste / BDO", "Environmental advisory", "Safety training", "Something else"],
      form_message: "Message",
      form_submit: "Send message",
      form_success: "Thanks! I'll get back to you within 24 hours.",
      errors: {
        name: "Please enter your name",
        email: "Please enter a valid email",
        message: "Write a few sentences so I know how to help",
      },
      contact_blocks: [
        { t: "Email", v: "kontakt@ecosafe.com.pl" },
        { t: "Phone", v: "+48 791 045 130" },
        { t: "Hours", v: "Mon–Fri · 9:00–17:00" },
        { t: "NIP", v: "6443343386" },
        { t: "REGON", v: "542094091" },
      ],
    },
  },
};

window.COPY = COPY;
